export const PERMISSIONS = {
  dashboardRead: "dashboard.read",
  customersRead: "customers:read",
  usersRead: "users.read",
  usersCreate: "users.create",
  usersUpdate: "users.update",
  usersDisable: "users.disable",
  devicesRead: "devices.read",
  devicesCreate: "devices.create",
  devicesUpdate: "devices.update",
  devicesDelete: "devices.delete",
  deviceInventoryRead: "device-inventory.read",
  deviceInventoryCreate: "device-inventory.create",
  deviceInventoryUpdate: "device-inventory.update",
  suppliersRead: "suppliers.read",
  suppliersCreate: "suppliers.create",
  suppliersUpdate: "suppliers.update",
  suppliersDelete: "suppliers.delete",
  inventoryLoadsRead: "inventory.loads.read",
  inventoryLoadsCreate: "inventory.loads.create",
  kitsRead: "kits.read",
  kitsCreate: "kits.create",
  kitsUpdate: "kits.update",
  kitsDelete: "kits.delete",
  rolesRead: "roles.read",
  rolesCreate: "roles.create",
  rolesUpdate: "roles.update",
  rolesDelete: "roles.delete",
  settingsProtocolsRead: "settings.protocols.read",
  settingsProtocolsCreate: "settings.protocols.create",
  settingsProtocolsUpdate: "settings.protocols.update",
  settingsProtocolsDelete: "settings.protocols.delete",
  settingsDeviceTypesRead: "settings.device-types.read",
  settingsDeviceTypesCreate: "settings.device-types.create",
  settingsDeviceTypesUpdate: "settings.device-types.update",
  settingsDeviceTypesDelete: "settings.device-types.delete",
  settingsBrandsRead: "settings.brands.read",
  settingsBrandsCreate: "settings.brands.create",
  settingsBrandsUpdate: "settings.brands.update",
  settingsBrandsDelete: "settings.brands.delete",
} as const;

export type AppPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
    
