export const PERMISSIONS = {
  dashboardRead: "dashboard.read",
  customersRead: "customers:read",
  usersRead: "users.read",
  usersCreate: "users.create",
  usersUpdate: "users.update",
  usersDisable: "users.disable",
  devicesRead: "devices.read",
  devicesCreate: "devices.create",
  devicesUpdate: "devices.update",
  devicesDelete: "devices.delete",
  deviceInventoryRead: "device-inventory.read",
  deviceInventoryCreate: "device-inventory.create",
  deviceInventoryUpdate: "device-inventory.update",
  suppliersRead: "suppliers.read",
  suppliersCreate: "suppliers.create",
  suppliersUpdate: "suppliers.update",
  suppliersDelete: "suppliers.delete",
  inventoryLoadsRead: "inventory.loads.read",
  inventoryLoadsCreate: "inventory.loads.create",
  kitsRead: "kits.read",
  kitsCreate: "kits.create",
  kitsUpdate: "kits.update",
  kitsDelete: "kits.delete",
  rolesRead: "roles.read",
  rolesCreate: "roles.create",
  rolesUpdate: "roles.update",
  rolesDelete: "roles.delete",
  companiesRead: "companies.read",
  companiesCreate: "companies.create",
  companiesUpdate: "companies.update",
  companiesDelete: "companies.delete",
  settingsProtocolsRead: "settings.protocols.read",
  settingsProtocolsCreate: "settings.protocols.create",
  settingsProtocolsUpdate: "settings.protocols.update",
  settingsProtocolsDelete: "settings.protocols.delete",
  settingsDeviceTypesRead: "settings.device-types.read",
  settingsDeviceTypesCreate: "settings.device-types.create",
  settingsDeviceTypesUpdate: "settings.device-types.update",
  settingsDeviceTypesDelete: "settings.device-types.delete",


  //Aqui iran los permisos para lo que tenga que ver con el customer
  settingsTicketCategoriesRead: "settings.ticket-categories.read",
  settingsTicketCategoriesCreate: "settings.ticket-categories.create",
  settingsTicketCategoriesUpdate: "settings.ticket-categories.update",
  settingsTicketCategoriesDelete: "settings.ticket-categories.delete",
  settingsBrandsRead: "settings.brands.read",
  settingsBrandsCreate: "settings.brands.create",
  settingsBrandsUpdate: "settings.brands.update",
  settingsBrandsDelete: "settings.brands.delete",
  settingsChecklistTemplatesRead: "settings.checklist-templates.read",
  settingsChecklistTemplatesCreate: "settings.checklist-templates.create",
  settingsChecklistTemplatesUpdate: "settings.checklist-templates.update",
  settingsChecklistTemplatesDelete: "settings.checklist-templates.delete",
  settingsChecklistItemsCreate: "settings.checklist-items.create",
  settingsChecklistItemsUpdate: "settings.checklist-items.update",
  settingsChecklistItemsDelete: "settings.checklist-items.delete",
  siteSurveyRead: "site_survey.read",
  siteSurveyCreate: "site_survey.create",
  accountUpdate: "account.update",
  settingsLogsRead: "settings.logs.read",
  ticketsRead: "tickets.read",
  ticketsUpdate: "tickets.update",
  ticketsAssign: "tickets.assign",
  ticketsComment: "tickets.comment",
  budgetsRead: "budgets.read",
} as const;

export type AppPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
    
